In [46]:
import numpy as np 
import pandas as pd

In [47]:
df = pd.read_csv("D:\Regex\covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [48]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [50]:
df=df.dropna()

In [51]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
lb = LabelEncoder()

In [55]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

C:\Users\furza\AppData\Local\Temp\ipykernel_22204\1186540942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = lb.fit_transform(df['gender'])
C:\Users\furza\AppData\Local\Temp\ipykernel_22204\1186540942.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cough'] = lb.fit_transform(df['cough'])
C:\Users\furza\AppData\Local\Temp\ipykernel_22204\1186540942.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'] = lb.fit_transform(df['city'])
C:\Users\furza\AppData\Local\Temp\ipykernel_22204\1186540942.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_covid'] = lb.fit_transform(df['has_covid'])

In [56]:
x=df.drop(columns=['has_covid'],axis=1)
x.head()

   age  gender  fever  cough  city
0   60       1  103.0      0     2
1   27       1  100.0      0     1
2   42       1  101.0      0     1
3   31       0   98.0      0     2
4   65       0  101.0      0     3

In [57]:
y=df['has_covid']
y

0     0
1     1
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    1
Name: has_covid, Length: 90, dtype: int32

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [60]:
x_train.head()

    age  gender  fever  cough  city
57   49       0   99.0      1     0
70   68       0  101.0      1     1
81   65       1   99.0      0     1
77    8       0  101.0      0     2
84   69       0   98.0      1     3

In [61]:
print("Total dataset = " , df.shape)
print("Independent data = " , x.shape)
print("Dependent data = " , y.shape)
print("Independent training data = " , x_train.shape)
print("Independent testing data = " , x_test.shape)
print("Dependent training data = " , y_train.shape)
print("Dependent testing data = " , y_test.shape)

Total dataset =  (90, 6)
Independent data =  (90, 5)
Dependent data =  (90,)
Independent training data =  (72, 5)
Independent testing data =  (18, 5)
Dependent training data =  (72,)
Dependent testing data =  (18,)

In [62]:
np.round(x_train.describe() , 1)

        age  gender  fever  cough  city
count  72.0    72.0   72.0   72.0  72.0
mean   43.5     0.4  100.7    0.3   1.2
std    25.3     0.5    2.1    0.5   1.0
min     5.0     0.0   98.0    0.0   0.0
25%    19.8     0.0   99.0    0.0   0.0
50%    47.0     0.0  101.0    0.0   1.0
75%    65.2     1.0  102.2    1.0   2.0
max    83.0     1.0  104.0    1.0   3.0

In [63]:
from sklearn.preprocessing import MinMaxScaler

In [64]:
mn = MinMaxScaler()

In [65]:
x_train_mn = mn.fit_transform(x_train)

In [67]:
x_train_new=pd.DataFrame(x_train_mn,columns=x_train.columns)

In [69]:
np.round(x_train_new.describe(),1)

        age  gender  fever  cough  city
count  72.0    72.0   72.0   72.0  72.0
mean    0.5     0.4    0.5    0.3   0.4
std     0.3     0.5    0.4    0.5   0.3
min     0.0     0.0    0.0    0.0   0.0
25%     0.2     0.0    0.2    0.0   0.0
50%     0.5     0.0    0.5    0.0   0.3
75%     0.8     1.0    0.7    1.0   0.7
max     1.0     1.0    1.0    1.0   1.0

In [70]:
from sklearn.preprocessing import StandardScaler

In [71]:
sc = StandardScaler()

In [72]:
x_train_sc = sc.fit_transform(x_train)

In [73]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [74]:
np.round(x_train_new.describe(),1)

        age  gender  fever  cough  city
count  72.0    72.0   72.0   72.0  72.0
mean   -0.0    -0.0   -0.0    0.0   0.0
std     1.0     1.0    1.0    1.0   1.0
min    -1.5    -0.8   -1.3   -0.7  -1.2
25%    -0.9    -0.8   -0.8   -0.7  -1.2
50%     0.1    -0.8    0.1   -0.7  -0.2
75%     0.9     1.3    0.7    1.4   0.7
max     1.6     1.3    1.6    1.4   1.7